package generaloss.networkforge.tcp.event;

public enum ErrorSource {

    CONNECT_CALLBACK,
    DISCONNECT_CALLBACK,
    RECEIVE_CALLBACK,
    ERROR_CALLBACK,

    PROCESSOR_CONNECT_CALLBACK,
    PROCESSOR_DISCONNECT_CALLBACK,
    PROCESSOR_RECEIVE_CALLBACK,
    PROCESSOR_ERROR_CALLBACK

}
