package generaloss.networkforge.tcp.listener;

public enum TCPErrorSource {

    CONNECT_CALLBACK,
    DISCONNECT_CALLBACK,
    RECEIVE_CALLBACK,
    ERROR_CALLBACK,

    PROCESSOR_CONNECT_CALLBACK,
    PROCESSOR_DISCONNECT_CALLBACK,
    PROCESSOR_RECEIVE_CALLBACK,
    PROCESSOR_ERROR_CALLBACK

}
